dotnet run ..\examples\HelloWorld.lox
dotnet run ..\examples\blocks\MultipleNestedBlocks.lox
dotnet run ..\examples\class\CallInheritedMethod.lox
dotnet run ..\examples\class\ClassMethodCall.lox
dotnet run ..\examples\class\ClassWithInit.lox
dotnet run ..\examples\class\ComplicatedThisResolution.lox
dotnet run ..\examples\class\InstanceCanAccessItsStateFromItsMethods.lox
dotnet run ..\examples\class\InstanceWithProperties.lox
dotnet run ..\examples\class\OverrideMethod.lox
dotnet run ..\examples\class\PrintClass.lox
dotnet run ..\examples\class\PrintInstance.lox
dotnet run ..\examples\class\PrintThis.lox
dotnet run ..\examples\class\SuperLookupStartsInClassContainingSuper.lox
dotnet run ..\examples\functions\Fibonacci.lox
dotnet run ..\examples\functions\FunctionsCloseOverFreeVariablesCorrectly.lox
dotnet run ..\examples\functions\FunctionWithReturn.lox
dotnet run ..\examples\functions\NestedFunctions.lox
dotnet run ..\examples\functions\PrintFunction.lox
dotnet run ..\examples\functions\PrintResultOfFunctionWithoutReturn.lox
dotnet run ..\examples\functions\RecursiveFunction.lox
dotnet run ..\examples\functions\ReturnFromNestedBlocks.lox
dotnet run ..\examples\logical\operators
dotnet run ..\examples\logical\operators\IfOperator.lox
dotnet run ..\examples\logical\operators\LogicalOperators.lox
dotnet run ..\examples\loops\ForLoop.lox
dotnet run ..\examples\loops\WhileLoop.lox
dotnet run ..\examples\statements\SimplePrintStatements.lox
dotnet run ..\examples\variables\GlobalVariable.lox
dotnet run ..\examples\variables\MultipleVariables.lox
dotnet run ..\examples\variables\RedefineGlobalVariable.lox
dotnet run ..\examples\variables\UninitializedVariable.lox